[pytest]
markers =
    smoke: быстрые тесты
    regression: регресионые тесты
    slow: медленные тесты
    api: api тесты
    movie: movie тесты
    ui: Юзер интерфейс тесты
    db: Тесты с базой данных